/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
///         Author:    Just Be Nice studio
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.justbenicestudio.com/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustomIcon {
  CustomIcon._();

  static const _kFontFam = 'MyFlutterApp';

  static const IconData leak_remove = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData directions_run = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData directions_bike = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData rowing = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData directions_walk = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData logout = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData wechat = const IconData(0xf1d7, fontFamily: _kFontFam);
  static const IconData heartbeat = const IconData(0xf21e, fontFamily: _kFontFam);
  static const IconData hand_peace_o = const IconData(0xf25b, fontFamily: _kFontFam);
  static const IconData swimming = const IconData(0xe838, fontFamily: _kFontFam);
  static const IconData isight = const IconData(0xf039, fontFamily: _kFontFam);

}
